version: "3"
services:
  webapp:
    image: savantly/test:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "/app/src/Home.py", "--logger.level=debug"]
    ports:
      - 8501:8501
    environment:
      - ANALYTICS_DB_HOST=${ANALYTICS_DB_HOST:-db}
      - ANALYTICS_DB_USER=${ANALYTICS_DB_USER:-postgres}
      - ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD:-postgres}
      - ANALYTICS_DB_DATABASE=${ANALYTICS_DB_DATABASE:-postgres}
      - ANALYTICS_DEV_MODE=${ANALYTICS_DEV_MODE:-true}
      - ANALYTICS_DEV_ROLE=${ANALYTICS_DEV_ROLE:-ADMIN}
    volumes:
      - .:/app
  
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    command: >
      --config /oauth2-proxy.cfg --set-xauthrequest=true
      --http-address="0.0.0.0:4180"
      --cookie-secret="0123456789tE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX8w="
      --cookie-refresh="3h"
      --email-domains="*"
      --cookie-secure="false"
      --upstreams="http://webapp:8501"
      --client-secret="hsJUXnO1e1T0o6FEFxOLq0cMvY4VyzWO"
      --client-id="analytics"
      --redirect-url="http://localhost:4180/oauth2/callback"
      --oidc-issuer-url="https://localhost:8081/realms/master"
      --provider="oidc"
      --provider-display-name="Savantly Project"
      --pass-access-token=true
      --skip-auth-routes="^/_stcore/health,^/_stcore/allowed-message-origins,^/*/_stcore/health,^/*/_stcore/allowed-message-origins"
    hostname: oauth2-proxy
    restart: unless-stopped
    depends_on:
      - webapp
    ports:
      - 4180:4180/tcp

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@savantly.net
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - db


  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: 
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8081:8080
    #volumes:
    #  - ./docker/keywind.jar:/opt/keycloak/providers/keywind.jar
    #  - ./themes/custom:/opt/keycloak/themes/custom
    depends_on:
      - postgres